# name: pipeline1

# on:
#   push:
#     branches:
#       - main

# jobs:
#   run-python-code:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v7

#       - name : run python version
#         run : python --version

#       - name: set up python version
#         uses: actions/setup-python@v7
#         with:
#           python-version: "3.13"
      
#       - name : run python version
#         run : python --version

#       - name: Run Python program
#         run: python welcome.py

name: ETL Pipeline

on:
  push:
    branches:
      - main
# jobs:
  # extract-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v7
  #     - name: Run Extract Job
  #       run: python extract.py

  # transform-job:
  #   needs: extract-job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v7
  #     - name: Run Transform Job
  #       run: python transform.py
  # load-job:
  #   needs: transform-job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v7
  #     - name: Run Load Job
  #       run: python load.py

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job1"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job2"
  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job3"
  job4:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job4"
  job5:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job5"
  job6:
    needs: [job4, job5]
    runs-on: ubuntu-latest
    steps:
      - name: run python code
        run: echo "job6"


